name: 🎭 Tests
on:
  push:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - master

jobs:
  silverstripe-module-4:
    name: 🧰 Silverstripe Module Testsuite v4
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module.yml@4
    with:
      phpunit: false
      phpstan: true
      phpcs: true
  silverstripe-module-5:
    name: 🧰 Silverstripe Module Testsuite v5
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module.yml@5
    with:
      phpunit: false
      phpstan: true
      phpcs: true
  # silverstripe-client:
  #   name: 📦 Client Testsuite
  #   uses: syntro-opensource/workflows/.github/workflows/client.yml@master
  #   with:
  #     eslint: true
  #     eslint_dir: client/src/seo-field/
  #     eslint_configfile: client/src/seo-field/.eslintrc
      # eslint_ext:
      # eslint_max-warnings:
      # stylelint: true
      # stylelint_glob: client/src/seo-field/**/*.scss
      # stylelint_max-warnings:
